name: Vality basic linters

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  lint:
    uses: valitydev/java-workflows/.github/workflows/basic-linters.yml@v1
