name: Maven Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: valitydev/java-workflow/.github/workflows/maven-service-build.yml@v4
    secrets:
      action-fetch-token: ${{ secrets.ACTIONS_FETCH_TOKEN }}
      github-pkg-ro-pat: ${{ secrets.GH_PACKAGES_RO_PAT2 }}
      github-pkg-ro-user: 'empayre-bot'
      mm-sa-wh-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}